### ISSUE TITLE
Steal per item

### ISSUE THREAD

**Issue by Driesboy** [Wurst-Imperium/Wurst-MC-1.11#10]
wait 0,1 sec before stealing the following item

**Comment by Driesboy** [comment]
why not?

Op 24-dec.-2016 16:17 schreef "Alexander01998" <notifications@github.com>:

**Comment by Driesboy** [comment]
the most servers block this steal

Op 24-dec.-2016 16:17 schreef "Alexander01998" <notifications@github.com>:

**Comment by CisBetter** [comment]
To bypass **Anti Cheat plugins** just set `YesCheatPlus` to `NoCheat+`, `AntiCheat`, etc.
This adds the delay you requested and makes other mods bypass the selected plugin, too.

**Comment by Driesboy** [comment]
ow ok

Op 24-dec.-2016 17:04 schreef "C is better" <notifications@github.com>:
