### ISSUE TITLE
minecraft.patch invalid

### ISSUE THREAD

**Issue by sudofox** [Wurst-Imperium/Wurst-MC-1.11#3]
The following two sections of the patchfile do not work properly with `git apply` ("patch does not apply") and must be added in separately.

Tested with decompiled source from MCP 5.35-r1; I can't see any reason why it wouldn't work properly, but the rest of the patches work fine.

```
@@ -346,6 +351,12 @@ public class GuiIngame extends Gui
             this.renderScoreboard(scoreobjective1, scaledresolution);
         }
         
+		// TODO: Client
+		else
+			ArenaBrawlMod.scoreboard = null;
+		if(!this.mc.gameSettings.showDebugInfo)
+			UIRenderer.renderUI(zLevel);
+
         GlStateManager.enableBlend();
         GlStateManager.tryBlendFuncSeparate(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA, GlStateManager.SourceFactor.ONE, GlStateManager.DestFactor.ZERO);
         GlStateManager.disableAlpha();
@@ -1926,6 +1929,11 @@ public abstract class EntityLivingBase extends Entity
     {
         this.motionY = (double)this.getJumpUpwardsMotion();
         
+		// TODO: Client
+		HighJumpMod highJumpMod = WurstClient.INSTANCE.mods.highJumpMod;
+		if(this instanceof EntityPlayer && highJumpMod.isActive())
+			this.motionY += highJumpMod.jumpHeight * 0.1F;
+
         if (this.isPotionActive(MobEffects.JUMP_BOOST))
         {
             this.motionY += (double)((float)(this.getActivePotionEffect(MobEffects.JUMP_BOOST).getAmplifier() + 1) * 0.1F);
```

Command used to test patch:

```
git apply --ignore-space-change --ignore-whitespace ..\patch\minecraft.patch
```

**Comment by crafter6789** [comment]
I've run into a lot of these. Rather than try with git, I have used eclipse's "Apply Patch" function and manually sorted out the problems. If you do it this way, you have to put the vanilla source into a folder called "a" so all the packages look like "a.net.minecraft.whatever". Rather inefficient, but if you know what parts of the vanilla code to replace with patch code, it is doable.

**Comment by LeafHacker** [comment]
I can also reproduce this issue. There are two sections of the patch file that do not apply and have to be done manually. I would expect generating a new patch would fix the issue.

**Comment by mkdsk** [comment]
@Alexander01998 please don't just close this, this is a minor nuisance but annoying.
