### ISSUE TITLE
Returning to server list after clicking Reconnect or using AutoReconnect requires multiple clicks of the "Back to server list" button.

### ISSUE THREAD

**Issue by sudofox** [Wurst-Imperium/Wurst-MC-1.11#4]
Returning to server list after clicking Reconnect or using AutoReconnect requires multiple clicks of the "Back to server list" button. The number of clicks required is equivalent to the number of times which you've selected Reconnect or have had AutoReconnect attempt to connect.

**Comment by crafter6789** [comment]
Here's a fix for that in net.minecraft.gui.GuiDisconnected:
`    protected void actionPerformed(GuiButton button) throws IOException
    {
        if (button.id == 0)
        {
        	// TODO: Client
        	if(this.parentScreen instanceof GuiDisconnected)
        	{
                this.mc.displayGuiScreen(new GuiMultiplayer(new GuiWurstMainMenu()));
        	}
        	else
        	{
        		this.mc.displayGuiScreen(this.parentScreen);
        	}
            
			// TODO: Client
		}else if(button.id == 1)`

**Comment by DesWurstes** [comment]
@Alexander01998 I'm working on a mod, I have to stop a thread. Do you have another way or is it okay if I declare a custom Exception?
