### ISSUE TITLE
1.11 inventory changes

### ISSUE THREAD

**Issue by v0idst4r** [Wurst-Imperium/Wurst-MC-1.11#7]
In 1.11 instead of empty slots being null, they are air.
Checks for stack != null or stack == null should be replaced with stack.getItem() != Items.AIR or stack.getItem() == Items.AIR
This will fix alot of issues where the client thinks you need to clear a slot. KillerPotion for example.
I would try to commit this myself but I don't know how to change the encoding used when editing on the site.

**Comment by crafter6789** [comment]
The AIR item actually isn't in Items.class, as air is a block, so one simple fix I came up with is replacing "stack == null" or the like with a new method: "stack.isEmpty()". This method would be in ItemStack.class, and would be as follows:
```
    // TODO: Client
    public boolean isEmpty()
    {
        return this.item == Item.getItemFromBlock(Blocks.AIR);
    }
```

**Comment by v0idst4r** [comment]
Yeah that's even better.
