### ISSUE TITLE
TrollPotion, KillerPotion & CrashChest Issue

### ISSUE THREAD

**Issue by Mhowser** [Wurst-Imperium/Wurst-MC-1.11#8]
As you can see in the video provided, these items are added successfully to my inventory in version 4.7 (1.10). however, in versions 5.0-5.1 (1.11) they fail to be added to the inventory. This was tested in single player mode.

 link to video: https://www.youtube.com/watch?v=Kdx9IGiT9rk

**Comment by v0idst4r** [comment]
#7
